# .github/workflows/generate.yml
# GitHub Actions configuration file for generating performance profiles
# See https://github.com/ragonneau/cutest-action for details

name: generate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  generate:
    name: Generate performance profiles
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Install CUTEst
        uses: ragonneau/cutest-action@v1.0.1

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install texlive-full --fix-missing
          python -m pip install -r requirements.txt
          git clone https://github.com/ragonneau/cobyqa.git
          cd cobyqa
          python -m pip install .
          cd ..
          python main.py
          rm -rf
          find archives -type f -name *.csv -exec rm -rf {} \;

      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          path: archives/performance/
